### ISSUE TITLE
GBP and 2022

### ISSUE THREAD

**Issue by davidwhicker** [evandiewald/helium-taxable-mining-earnings#6]
Good day

Great tool tahnk you. I dont suppose support for GBP and 2022 can be added? or just somewhere / way I can download CSV for 2022 like you have for the 2021.

**Comment by evandiewald** [comment]
I can work on adding additional currencies and support more arbitrary date ranges.
Also, let me know if you're able to access this query on the DeWi ETL, which should be much faster (again, sorry it's USD - this is how oracle prices are stored on-chain):
https://etl.dewi.org/question/2151-usd-earned-by-day

**Comment by cparkus** [comment]
I came here to see if anyone has requested other dates as well! The UK income tax period is 6 April to 5 April, hence why we're looking to be able to pull data for 2022 (even if the calendar year isn't over yet). You've built a brilliant tool, I've subscribed to this issue so look forward to seeing the fix! Do you want to post your wallet ID? I'd be happy to send you some tokens as a thanks.
